### ISSUE TITLE
can't handle comment lines

### ISSUE THREAD

**Issue by wrfranklin** [FlamingTempura/bibtex-tidy#1]
Throws an error on comment lines; that is, lines starting with a semicolon.

**Comment by FlamingTempura** [comment]
Could you give an example of a bibtex text which fails but should work? I can't find any bibtex documentation which says a semicolon can be used as a comment.

**Comment by craymichael** [comment]
So, while personally I do not like it, the BibTeX standard is to only have two contexts: inside and outside of an entry. Everything inside an entry, that is, a starting **`@{`** and a closing **`}`**, is treated as key/value pairs of an entry, while everything outside is treated as a comment. I always use **`%`** to be consistent with tex comments, but technically anything could be used (except for **`@`**).

Source: [Summary of BibTeX](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#comment)

**Comment by FlamingTempura** [comment]
Thanks for the link, much more comprehensive than the resources I had been using when designing the bibtex parser. 

This should now be fixed  - feel free to try it on https://flamingtempura.github.io/bibtex-tidy/
