### ISSUE TITLE
Error in removing duplicates

### ISSUE THREAD

**Issue by Ruchirajput19** [FlamingTempura/bibtex-tidy#11]
Hi!

It is a wonderful tool to tide up bib file. But while checking for duplicates, I noticed that two unique entries in my file were erroneously merged into one. The entries are listed here for your reference.

@article{Raku2,
	title          = {Focusing of a vortex carrying beam with Gaussian background by a lens in the presence of spherical aberration and defocusing},
	author         = {R.K.Singh and P.Senthilkumaran and K. Singh},
	year           = 2007,
	journal        = {Optics and Lasers in Engg.,},
	volume         = 45,
	pages          = {773--782},
	date-added     = {2020-05-09 00:08:30 +0530},
	date-modified  = {2020-05-09 00:10:16 +0530}
}

@article{Raku10,
	title          = {Focusing of a vortex carrying beam with Gaussian background by an apertured system in presence of coma},
	author         = {R.K.Singh and P.Senthilkumaran and K. Singh},
	year           = 2008,
	journal        = {Opt.Commun.},
	volume         = 281,
	pages          = {923--934},
	date-added     = {2020-05-09 00:13:37 +0530},
	date-modified  = {2020-05-09 00:14:50 +0530}
}

Notice that titles of the articles are quite similar, but they are in unique journals. Is it possible to check for duplicates based on journal and year criterion as well?

**Comment by FlamingTempura** [comment]
Thanks for raising this! Your examples were being detected as duplicates because the duplicate checker was only looking at the first 50 characters of the title. I've pushed a fix so that the entire title is used. Give it a try and see if this fixes your issue.

**Comment by Ruchirajput19** [comment]
Wonderful!
It's working properly now.

Thanks a lot!!
