### ISSUE TITLE
Making .original file optional, --quiet mode?

### ISSUE THREAD

**Issue by tony** [FlamingTempura/bibtex-tidy#12]
Hi!  Thank you for the project @FlamingTempura !

Are you open to making an option (e.g. `--no-backup`) to support not creating a `.original` file when using the script? 

Also, are you open to having a `--quiet` mode, that doesn't output to stdout/stderr?

For context: I'm using this as a formatter in vim ([link](https://github.com/tony/vim-config-framework/commit/28bd4cdd3b3f6c7382235ab28380a109431fb5fd), [link 2 for removing .original file](https://github.com/tony/vim-config-framework/commit/c8d693c297da742c1ee0e0ddef4b13617486442e))

**Comment by FlamingTempura** [comment]
Great ideas. 

I've just added `--no-backup` and `--quiet`, so give them a try.

**Comment by tony** [comment]
Nice @FlamingTempura. That worked out perfectly! Thank you!

Both flags work for me.

**Comment by tony** [comment]
Oh, I will close this issue. (I assume it's considered fixed at this point)

Have a good night over there!
