### ISSUE TITLE
Bug with commands in fields?

### ISSUE THREAD

**Issue by renefritze** [FlamingTempura/bibtex-tidy#127]
With this input
```
@misc{TheKey,
   title        = {{The \textsf{Secret}}},                          
}
```

and these options
```
bibtex-tidy --curly --space=2 --align=13 --no-escape --no-tidy-comments --no-remove-dupe-fields --no-lowercase --enclosing-braces=title
```

the online bibtex-tidy outputs
```
@misc{TheKey,
  title        = {{The \textsfSecret}}
}
```

I expected no change, but the "inner" curly braces were stripped.
Is this a bug or is my expectation wrong?

**Comment by FlamingTempura** [comment]
Thanks for the report - that does appear to be a bug. It should not be removing the braces.

**Comment by FlamingTempura** [comment]
Finally got around to fixing this. 

Braces that are part of commands will now be maintained in output:
```bibtex
@misc{TheKey,
  title        = {{The \textsf{Secret}}}
}
```
