### ISSUE TITLE
Allow file list

### ISSUE THREAD

**Issue by lcnittl** [FlamingTempura/bibtex-tidy#13]
Do you think it would be possible to change the behavior of `bibtex-tidy` so that it accepts a list of files as CLI arguments, rather than only a single file?

```
bibtex-tidy [file1 [file2 [..]]
```

Thanks for your consideration!

**Comment by FlamingTempura** [comment]
Thanks for the suggestion.

What would you expect to happen when specifying multiple files?
* Each file is tidied and overwrites the original file
* The files are combined into a single new bibtex file

**Comment by lcnittl** [comment]
Option 1, so each file is independently tidied and overwrites the respective original file.

This would eventually enable to use `bibtex-tidy` as hook for [`ppre-commit`](https://pre-commit.com/) for automated tidying of al .bib files in a repo on commit.

**Comment by lcnittl** [comment]
The only thing that would then (after enabling list of files) be missing for the use as pre-commit hook is a `.pre-commit-hooks.yaml` file, as I have added in [my fork](https://github.com/lcnittl/bibtex-tidy/blob/master/.pre-commit-hooks.yaml). This file is static, and after adding it once does not have to be touches anymore.

**Comment by FlamingTempura** [comment]
Sounds good, I'll work on adding file list support when I get a chance (I've not been working with bibtex lately).

Feel free to open a pull request for the pre commit hook.

**Comment by lcnittl** [comment]
Thanks a lot for working on it! PR is created (#14).

**Comment by FlamingTempura** [comment]
Finally got around to working on this. It's landed now in v1.4.0, so please try it out!
