### ISSUE TITLE
Extra empty line when wrapping long non-breakable lines

### ISSUE THREAD

**Issue by mcnesium** [FlamingTempura/bibtex-tidy#141]
Here is the result of tidying a snippet with a very long line. It creates an extra empty line when doing `--wrap` or using the equivalent option in the browser app:

    @online{flaming2021tidy,
        url = {
            
            https://web.archive.org/web/20211230024101/https://flamingtempura.github.io/bibtex-tidy/
        }
    }

The empty line should not be there, right?

**Comment by FlamingTempura** [comment]
Thanks for the report - that does look like a bug.

**Comment by FlamingTempura** [comment]
This should now be fixed
