### ISSUE TITLE
Support output to stdout

### ISSUE THREAD

**Issue by cristobaltapia** [FlamingTempura/bibtex-tidy#143]
Hi, I think that i would be useful to have an option to print the formatted bibfile to stdout. This would be useful e.g. to for using within texteditors such as vim. Currently the file always gets overwritten, and depending on the individual configuration of the editor it might no get updated automatically.

**Comment by mcnesium** [comment]
It does work when appending a dash. Here is a config snipped for VSCode when using [Custom Local Formatters](https://open-vsx.org/extension/jkillian/custom-local-formatters) extension:

      "customLocalFormatters.formatters": [
        {
          "command": "bibtex-tidy --no-backup -",
          "languages": [
            "bibtex"
          ]
        }
      ]

**Comment by cristobaltapia** [comment]
This does not work for me. The file is still being overwritten.
I use `efm-langserver` with `coc.nvim` in neovim with this configuration:

`~/.confg/efm-langserver/config.yaml`
```yaml
languages:
  bib:
    format-command: 'bibtex-tidy --no-backup -'
```

`~/.config/nvim/coc-settings.json`
```json
  "languageserver": {
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["bib"]
    },
}
```

I don't think that adding the `-` is really redirecting the output to stdout. If I do 

```bash
bibtex-tidy --no-backup - bibfile.bib > test.log
```

I get nothing in `test.log`. If I do 

```bash
bibtex-tidy --no-backup bibfil.bib > test.log
```

I get something like

```
Tidying...
{citations here}

Done. Successfully tidied 36 entries.
```

So you always have this `Tidying....` at the top and `Done....` at the bottom. And the original file is still rewritten.

**Comment by schneiderfelipe** [comment]
The `-` indicates that `bibtex-tidy` will get data from the standard input. In this case, it will output to the stdout. Try:

```console
$ cat some.bib | bibtex-tidy [options here] - > test.log
```

This seems to solve the mystery for me. Works fine with @helix-editor, will probably work with @vim / @neovim as well.

**Comment by FlamingTempura** [comment]
I'm thinking of adding a `--stdout` option to only output to stdout. I'm looking around at similar tools to see how they do it.

If I was starting this project again it would be stdout by default and an option to write in place (precluding the need to create backups)... but hey ho.

**Comment by FlamingTempura** [comment]
v1.10.0 just released that supports stdout as a preview feature without needing to specify `-`. For now you need to use the `--v2` flag.

Read from stdin, out to stdout:

`bibtex-tidy --v2 < untidy.bib > tidied.bib`

Read from file, out to stdout:

`bibtex-tidy --v2 untidy.bib > tidied.bib`

Let me know if there are any issues and I'll reopen the ticket.

**Comment by cristobaltapia** [comment]
Thanks! This works perfectly!
