### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by lcnittl** [FlamingTempura/bibtex-tidy#15]
Do you think it is possible to enable (by default, or as option) addition of a trailing comma (for an entry's last key-val pair)?

A reason on why this is useful is given in the [documentation of `black`](https://github.com/psf/black/blob/master/docs/the_black_code_style.md#how-black-wraps-lines):

> You might have noticed [...] that a trailing comma is always added. Such formatting produces smaller diffs; when you add or remove an element, it's always just one line.

It seems that also JabRef adds a trailing comma in files that it manipulates.

Thanks for your consideration!

**Comment by FlamingTempura** [comment]
Great idea - landed in v1.4.0 with option `--trailing-commas`
