### ISSUE TITLE
--help option does not work

### ISSUE THREAD

**Issue by nielskm** [FlamingTempura/bibtex-tidy#17]
Installing bibtex-tidy using npm on fedora 32 and running `bibtex-tidy --help` results in a `No option "--help"` although `bibtex-tidy -h` shows `--help` as an option (and not `-h`).

**Comment by FlamingTempura** [comment]
Thanks for the report! I've fixed this in c451c04 and released a new version (v1.4.2). Let me know if you have any trouble.
