### ISSUE TITLE
a

### ISSUE THREAD

**Issue by joshiCoding** [FlamingTempura/bibtex-tidy#177]

**Comment by FlamingTempura** [comment]
> Right now, if I ctrl-a the page, I am getting the whole of the page including the side option. So the only option to copy entire text the just got tidy is to manually go to the bottom to shift select which is very difficult for large files. Please add a copy all button that only copies my BibTeX and not the side button text.

It appears you've deleted your original feature request. But I agree this is a good suggestion so have added it. You will now find a copy icon top right of the editor.
