### ISSUE TITLE
Feature Request - Put titles in double curly brackets {{ }} to keep capital letters.

### ISSUE THREAD

**Issue by GillesC** [FlamingTempura/bibtex-tidy#18]
Feature Request - Put titles in double curly brackets {{ }} to keep capital letters.

**Comment by FlamingTempura** [comment]
Thanks for the suggestion! I like the sound of this and will take a look into it.

**Comment by FlamingTempura** [comment]
Feature added. You'll find it under "Enclose in double braces" in the editor or `--enclosing-braces` in the CLI.
