### ISSUE TITLE
FR: Removing & Filtering Entries

### ISSUE THREAD

**Issue by chrisgrieser** [FlamingTempura/bibtex-tidy#183]
This tool has so many useful commands, however, two quite basic operations seem to miss in my view: 
1) removing entries by citekey (or another field).
2) filter the library based on some criteria, e.g. only keeping entries where a field (not) matches a certain regex.

Number 2 would also be useful for BibTex refactoring in general.

**Comment by FlamingTempura** [comment]
I'm curious what the use cases for filtering entries might be. Could you give an example use case? E.g. would you want remove entries by a specific author?

**Comment by chrisgrieser** [comment]
removing all entries with a specific keyword could be quite useful, for example.

Another use case would be refactoring, e.g., splitting up a library into two libraries.

**Comment by FlamingTempura** [comment]
Thanks - appreciate the suggestion, it's an interesting idea. However, I'm inclined to say it doesn't fit within the scope of the project. bibtex-tidy focuses on tidying entries up. Filtering entries seems a bit to big to be called 'tidying' (as you say this is closer to refactoring).

**Comment by chrisgrieser** [comment]
sure thing! a lot of the features come close to refactoring, so I thought it might have been a useful addition :)
