### ISSUE TITLE
Some extra spacing between authors

### ISSUE THREAD

**Issue by Legorock** [FlamingTempura/bibtex-tidy#2]
Hi, 

Some entries, especially from CoRR, have extra space between authors when they have full name and surname separated with 'and'. Examples:
[https://dblp.uni-trier.de/rec/bibtex/journals/corr/abs-1811-02883](https://dblp.uni-trier.de/rec/bibtex/journals/corr/abs-1811-02883)
Anyway good work!

**Comment by Legorock** [comment]
I think the issue is more related to endlines

**Comment by FlamingTempura** [comment]
Thanks! I've just pushed a fix, so try it out and see if it works https://flamingtempura.github.io/bibtex-tidy/

**Comment by Legorock** [comment]
It seems like it is resolved. Thanks for the quick fix
