### ISSUE TITLE
add a shorten author list option

### ISSUE THREAD

**Issue by avivajpeyi** [FlamingTempura/bibtex-tidy#20]
Hi! Firstly, thanks for setting up this linter! it's great! 

I was wondering if it might be possible for you to add a feature to reduce the number of authors for bib entries. Example, the [Event Horizon M87 paper](https://iopscience.iop.org/article/10.3847/2041-8213/ab0ec7), or LIGO papers have too many authors. 

Maybe using something like this: https://gist.github.com/zimmerst/9cb2ccad69b5f55a0a222c01b1d8e183

**Comment by FlamingTempura** [comment]
Sounds like a useful feature, I'll take a look into it.

**Comment by FlamingTempura** [comment]
You should now see a max authors option in the UI (maxAuthors in the API, --max-authors on CLI)

![image](https://user-images.githubusercontent.com/1085434/105356246-0ee0fc80-5beb-11eb-8120-df298f8e3b1f.png)

Let me know if there are any problems!
