### ISSUE TITLE
Tidying keeps adding curly braces when 'Enclose in double braces' is active

### ISSUE THREAD

**Issue by norro** [FlamingTempura/bibtex-tidy#23]
When the `Enclose in double braces` option is active, e.g., for the `title` field _and_ the first or last part of the field is escaped with curly braces, tidying up keeps adding curly braces.

To reproduce, tidy up this entry with the `Enclose in double braces` option active for the `title` field:
```
@article{munk2020model,
	title        = {{{M}odel-{B}ased {S}afety {A}ssessment with {SysML} and {C}omponent {F}ault {T}rees: {A}pplication and {L}essons {L}earned}},
	author       = {Munk, Peter and Nordmann, Arne},
	year         = 2020,
	journal      = {Softw Syst Model},
	volume       = 19,
	pages        = {889--910},
	doi          = {10.1007/s10270-020-00782-w}
}
```

**Expected:**
Number of braces is unchanged by the tidy operation.

**Observed:**
It keeps adding braces on each tidy operation.

**Comment by FlamingTempura** [comment]
Thanks for the report. Finally got round to fixing this.

Output will now be:
```bibtex
@article{munk2020model,
	title        = {{Model-Based Safety Assessment with SysML and Component Fault Trees: Application and Lessons Learned}},
	author       = {Munk, Peter and Nordmann, Arne},
	year         = 2020,
	journal      = {Softw Syst Model},
	volume       = 19,
	pages        = {889--910},
	doi          = {10.1007/s10270-020-00782-w}
}
````

**Comment by norro** [comment]
Thank you very much!
