### ISSUE TITLE
FR: Option to add blank lines between entries

### ISSUE THREAD

**Issue by chrisgrieser** [FlamingTempura/bibtex-tidy#245]
Tiny Quality of Life improvement, but an option to add blank lines between entries would be useful, as at least for me, it increases readability. (As it's a trade-off with compactness, I'd solely make it an option)

**Comment by FlamingTempura** [comment]
Great suggestion, I've added this option. The option is called "Insert blank lines" in the web tool and `--blank-lines` on the CLI.

**Comment by mafsi** [comment]
I'm using in VIM the following:

```
nnoremap <localleader>bt :!bibtex-tidy --blank-lines --wrap=80 %:p<cr>
```
However, `--blank-lines` are not working:

``` 
Unknown option: --blank-lines
Try 'bibtex-tidy --help for more information

shell returned 1
```
