### ISSUE TITLE
Problem with "escape special characters"

### ISSUE THREAD

**Issue by ironcyborg** [FlamingTempura/bibtex-tidy#27]
Hello, thank you for this very useful tool! It is really helping with the quite huge bibliography of my PhD thesis!

Anyway, I'm afraid I found a small problem: when I enable "escape special characters", it works great on most entries, except when I have math content. By escaping dollar symbol, it breaks math strings. I got quite a headache to pinpoint the problem!

 For example, if I process this:
@article{ashikari:1999,
	title        = {Rice gibberellin-insensitive dwarf mutant gene Dwarf 1 encodes the **$\alpha$**-subunit of GTP-binding protein},
	author       = {Ashikari, Motoyuki and Wu, Jianzhong and Yano, Masahiro and Sasaki, Takuji and Yoshimura, Atsushi},
	year         = 1999,
	journal      = {Proceedings of the National Academy of Sciences},
	publisher    = {National Acad Sciences},
	volume       = 96,
	number       = 18,
	pages        = {10284--10289},
}

the software return:

@article{ashikari:1999,
	title        = {Rice gibberellin-insensitive dwarf mutant gene Dwarf 1 encodes the **\$\alpha\$**-subunit of GTP-binding protein},
	author       = {Ashikari, Motoyuki and Wu, Jianzhong and Yano, Masahiro and Sasaki, Takuji and Yoshimura, Atsushi},
	year         = 1999,
	journal      = {Proceedings of the National Academy of Sciences},
	publisher    = {National Acad Sciences},
	volume       = 96,
	number       = 18,
	pages        = {10284--10289}
}

..and then of course LaTeX gets angry! Now that I know I'll just keep an eye on suspicious "\$", I only wanted to let you know.
It's the only flaw I found, besides that it's perfect!

**Comment by FlamingTempura** [comment]
Thanks for the feedback. Glad it's helpful!

At the moment the bibtex parser does not parse the content of values. It just does a simple search and replace for each character listed [here](https://github.com/FlamingTempura/bibtex-tidy/blob/master/src/unicode.ts). As you discovered $ will always be escaped, even when used to enclose a math expression.

A simple option might be to not escape $ at all. The original intention of this option was to make up for the poorly escaped bibtex which gets exported from some journals. These could conceivably include an unescaped $ sign intended as a unit of currency.

Alternatively the parser could be built out to parse math expressions in values.

I'll take a look at some point, or I'd welcome a PR.
