### ISSUE TITLE
Remove several curly braces added by mistake

### ISSUE THREAD

**Issue by bernalde** [FlamingTempura/bibtex-tidy#28]
Sometimes, there are entries that have more than double curly braces. Cleaning those up would be nice :)
MWE:
`
@article{Zyngier2012,
  title    = {{{{UOPSS : A New Paradigm for Modeling Production Planning {\&} Scheduling Systems}}}},
  author   = {Zyngier, Danielle and Kelly, Jeffrey D},
  year     = 2012,
  journal  = {Symposium on Computer Aided Process Engineering},
  number   = {June},
  pages    = {17--20},
  keywords = {decision-making,modeling,optimization,planning,scheduling}
}`

(Added several curly braces by mistake when hitting tidy several times.

**Comment by FlamingTempura** [comment]
Thanks for the report. This should now be fixed (see similar bug in #23)

Above example will tidy to:
```bibtex
@article{Zyngier2012,
	title        = {{UOPSS : A New Paradigm for Modeling Production Planning \& Scheduling Systems}},
	author       = {Zyngier, Danielle and Kelly, Jeffrey D},
	year         = 2012,
	journal      = {Symposium on Computer Aided Process Engineering},
	number       = {June},
	pages        = {17--20},
	keywords     = {decision-making,modeling,optimization,planning,scheduling}
}
```
