### ISSUE TITLE
Small github.io bibtex-tidy example site edits

### ISSUE THREAD

**Issue by craymichael** [FlamingTempura/bibtex-tidy#3]
Very, very small issue. It would be great if on your example website that the following error were fixed:

In the sort entries by area, there is the text:
> (space delimited, e.g: id, type, publisher, author)

This was confusing at first as my input (exact same as the line) did not work. This should instead read:

> (space delimited, e.g: id type publisher author)

i.e. just remove the commas. Thanks for the very useful tool btw!

**Comment by craymichael** [comment]
To clarify I'm talking about [https://flamingtempura.github.io/bibtex-tidy/](https://flamingtempura.github.io/bibtex-tidy/)

**Comment by FlamingTempura** [comment]
Good catch! Fixed.
