### ISSUE TITLE
Remove all braces from fields

### ISSUE THREAD

**Issue by tobirolinew** [FlamingTempura/bibtex-tidy#33]
This is not a bug, but it would be useful to have an option within the "VALUES" block that can remove all braces from BibTeX fields. For example, the BibItem

```
@article{11Mellau,
  title = {Highly excited rovibrational states of {HNC}},
  author = {G. Ch. {M}ellau},
  year = {2011},
  journal = {J. Mol. Spectrosc.},
  volume = {269},
  pages = {77}
}
```

should be modified to 

```
@article{11Mellau,
  title = {Highly excited rovibrational states of HNC},
  author = {G. Ch. Mellau},
  year = {2011},
  journal = {J. Mol. Spectrosc.},
  volume = {269},
  pages = {77}
}
```

It would also help if one could control which fields are needed to be cleaned in terms of extra braces. 

Perhaps those braces which are part of math expressions (that is, surrounded with $$), should be retained.

Thank you in advance for considering this option.

**Comment by FlamingTempura** [comment]
Implemented a remove braces option which allows specifying fields to remove braces from.
