### ISSUE TITLE
Feature Request: Tidy up months field

### ISSUE THREAD

**Issue by xathon** [FlamingTempura/bibtex-tidy#351]
Pre-formatted citations seem to vary wildly how they format the month entry, and Bibtex *usually* seems to have no problem parsing them. From https://www.bibtex.com/f/month-field/ :
```
% preferred way is to use three-letter abbreviation macros
month = feb

% other ways
month = 2
month = "2"
month = {2}
month = "February"
month = {February}
```
However, there are also citations formatting the month field like this:
```
month = {aug}
```
Which causes warnings on compile.
I understand that fixing the latter is strictly speaking a refactor, and thus might be out of scope for the project. Still, it might be a worthwhile feature to reformat all (valid) month fields into one, selectable style.

**Comment by FlamingTempura** [comment]
Great suggestion. I've implemented this in the web UI, check out the new "Abbreviate months" option. 

```bibtex
@article{foo,
    month = 2,
    month = "2",
    month = {2},
    month = "February",
    month = {February},
}
```

Will become:
```bibtex
@article{foo,
	month        = feb,
	month        = feb,
	month        = feb,
	month        = feb,
	month        = feb
}
```

List of conversions here: https://github.com/FlamingTempura/bibtex-tidy/blob/master/src/months.ts#L18 Easy to extend later, e.g. for months in other languages.

This will be in the next CLI release as `--months`
