### ISSUE TITLE
Do not treat entries as duplicates if `number` field differs

### ISSUE THREAD

**Issue by Holzhaus** [FlamingTempura/bibtex-tidy#364]
I need to quote the NIST FIPS-186 standard in 2 different versions and followed the NIST reference format for citations (see the BibTex example under "NIST listed as the author"):

```bibtex
@techreport{fips186-2,
   author = {National Institute of Standards and Technology},
   title = {Digital Signature Standard (DSS)},
   institution = {U.S. Department of Commerce},
   address= {Washington, D.C.},
   number = {Federal Information Processing Standards Publications (FIPS PUBS) 186-2, Change Notice 1 October 05, 2001},
   date = {2000-01-27},
   url = {https://csrc.nist.gov/publications/detail/fips/186/2/archive/2001-10-05},
   urldate = {2022-10-27},
}
@techreport{fips186-4,
   author = {National Institute of Standards and Technology},
   title = {Digital Signature Standard (DSS)},
   institution = {U.S. Department of Commerce},
   address= {Washington, D.C.},
   number = {Federal Information Processing Standards Publications (FIPS PUBS) 186-4},
   date = {2013-07-19},
   doi = {10.6028/NIST.FIPS.186-4}
}
```
Unfortunately, when I use `--duplicates=doi,citation,key --merge=overwrite`, these two are identified as duplicates and merged. I suppose this is because author and title are the same. IMHO, the `number` field should also be considered when deciding if it's a duplicate or not.

**Comment by FlamingTempura** [comment]
Nice suggestion - this has now been implemented. The `citation` rule will only detect duplicates if two entries contain similar author and title and identical number (if available).

The above references will no longer be merged.

This is not yet released but it's available in the master branch.
