### ISSUE TITLE
Add option to redirect output to stdout instead of modifying file in place

### ISSUE THREAD

**Issue by mildblimp** [FlamingTempura/bibtex-tidy#37]
I work with an automatic formatter which needs the file to be outputted to stdout. Expected behaviour:
File `bibliography.bib`:
```
@Book{sweig42,
  Author =	 { Stefa{n} Sweig },
  title =	 { The impossible book },
  publisher =	 { Dead Poet Society},
  year =	 1942,
  month =        mar
}
```

```
bibtex-tidy --quiet --no-in-place bibliography.bib
```
Output:
```
@book{sweig42,
	title        = {The impossible book},
	author       = {Stefa{n} Sweig},
	year         = 1942,
	month        = mar,
	publisher    = {Dead Poet Society}
}
```
Or in many other tools you can do something like this `cat test.py | black --quiet -`, which reads the file from stdin and outputs the formatted file to stdout.

**Comment by IllTemperedMax** [comment]
I encountered the same need while working with git filters. They are expected to take file contents from stdin and write the filtered version to stdout.

**Comment by mildblimp** [comment]
I have a working version that uses the `rw` package. Should I make a pull request?
