### ISSUE TITLE
Install the github version

### ISSUE THREAD

**Issue by pietro-coretto** [FlamingTempura/bibtex-tidy#39]
For some reason I cannot run the `npm` installer on the current machine. If I clone the github version, how do I install it on a Linux system?

**Comment by FlamingTempura** [comment]
Installing via npm is the only approach that I support. What problems are you having with it?

There may be a package available on your distro package manager, e.g. there is an AUR package for arch.

**Comment by pietro-coretto** [comment]
Thanks, I could install it on my personal machine, but for some reason, `npm` is not allowed on the computing server I use for most of my work. So that's why I asked.
