### ISSUE TITLE
Faulty underscore escaping in URLs

### ISSUE THREAD

**Issue by blu3r4y** [FlamingTempura/bibtex-tidy#4]
BibTeX Tidy attempts to escape some characters (here: the underscore`_` by `\_`) in URLs, which does then break the URL. I encountered this problems with Biber. Biber allows `_` and fails with `\_`, though, BibTeX and BibLaTex may behave exactly in the opposite way.

As suggested [here](https://tug.org/pipermail/pdftex/2002-March/002379.html), underscores should rather be represented by their HTML encoding `%5F` which works fine for me in Biber (though, maybe someone should also test this with BibTeX and BibLaTex).

In general, using percent-encodings in URLs should always be supported (see [here](https://en.wikipedia.org/wiki/Percent-encoding)). I guess this would be a good strategy for all special characters in URL fields, not only underscores.

**Example:**

```
@book{mybook,
	title        = {My Book},
	author       = {John Doe},
	url          = {https://en.wikipedia.org/wiki/Underscore_(disambiguation)}
}
```

**Tidied-up example:**

```
@book{mybook,
	title        = {My Book},
	author       = {John Doe},
	url          = {https://en.wikipedia.org/wiki/Underscore\_(disambiguation)}
}
```

**Suggested correction:**

```
@book{mybook,
	title        = {My Book},
	author       = {John Doe},
	url          = {https://en.wikipedia.org/wiki/Underscore%5F_(disambiguation)}
}
```

**Comment by prasannjeet** [comment]
I would suggest to make escaping optional, as some editors such as TexStudio do not support escaped texts if used in a separate ".bib" file.

**Comment by FlamingTempura** [comment]
Added escaping URLs as an option

**Comment by blu3r4y** [comment]
Looks good to me, thank you! :)

**Comment by prasannjeet** [comment]
Perfect!
