### ISSUE TITLE
Please remove from sorting keys @string @xdata

### ISSUE THREAD

**Issue by mafsi** [FlamingTempura/bibtex-tidy#405]
`@xdata` & `@string` are also sorted when `--sort=key` is passed.

```
@string{ucp      = {University of California Press}}

@xdata{uchp,
  location      = {New York},
  publisher     = {University of Chicago Press}
}

...
rest of the `.bib` file

```

**Comment by FlamingTempura** [comment]
Any reason these should not be sorted? Personal preference or is the order important for biblatex?

**Comment by FlamingTempura** [comment]
Thanks for clarifying.

To explain how it works currently: `@string` blocks are treated the same as comments; they glue themselves to the next entry such that they remain above the same entry when sorted. `@xdata` has no special handling and is sorted the same as any other entry.

Here's my current proposal, keen to get your thoughts. We could allow you to specify `special` as a sort field to bring any special blocks (`@string`, `@xdata`, `@preamble`, `@set`) to the top of the file.

This could be combined with other sort fields, e.g. `special,key` to have special blocks at the top, then sort by key.

**Comment by mafsi** [comment]
I think your proposal is an excelent idea. Thanks for adding this, and thanks for your work!

**Comment by FlamingTempura** [comment]
As of v1.11.0 / current web UI, you can specify `special` as a sort field. I'll close this ticket, but let me know if there are any issues.

**Comment by mafsi** [comment]
Is working on the website. I'm waiting the NPM package to be updated. Thank a lot!
