### ISSUE TITLE
escape special characters

### ISSUE THREAD

**Issue by stepeos** [FlamingTempura/bibtex-tidy#412]
i have this example reference
@book{HITHERE,
	title        = {my very sepcial book},
	author       = {My favouriteAuthor},
	year         = 2011,
	publisher    = {This & That},
	isbn         = {1234567810},
	edition      = 1
}
As you can see, if any of the fields like publisher in this case, has special characters that are not escaped, then latex will crash and burn, trying to compile this.

Is it possible to automatically escape such characters like ampersand to `\&` ? 

EDIT:
I actually just saw, that this should be handled in [`function escapeSpecialCharacters(str)`](https://github.com/FlamingTempura/bibtex-tidy/blob/98701a8bfb5a98ccd3ed43db679f525714599d72/bibtex-tidy.js#L3042).
Is there a reason, that ampersand is not in the [`speicalCharacters`](https://github.com/FlamingTempura/bibtex-tidy/blob/98701a8bfb5a98ccd3ed43db679f525714599d72/bibtex-tidy.js#L713) ?

**Comment by FlamingTempura** [comment]
Apologies for delay in responding @stepeos - I've tried your example with the 'escape special characters' option enabled, and can confirm ampersand is escaped:

```bibtex
@book{HITHERE,
	title        = {my very sepcial book},
	author       = {My favouriteAuthor},
	year         = 2011,
	publisher    = {This \& That},
	isbn         = 1234567810,
	edition      = 1
}
```

Let me know if you're still seeing issues with this.
