### ISSUE TITLE
Doesn't escape space in path

### ISSUE THREAD

**Issue by ai4bing** [FlamingTempura/bibtex-tidy#416]
As described in the title, only recognize the first field before space
<img width="700" alt="Screenshot 2023-11-18 at 1 47 59 PM" src="https://github.com/FlamingTempura/bibtex-tidy/assets/76109691/73ba0c21-48eb-493f-90db-162516cdca94">

Same thing happens when using backslash \ to escape.

**Comment by FlamingTempura** [comment]
Fixed in v1.14.0
