### ISSUE TITLE
False positive in duplicate matchings

### ISSUE THREAD

**Issue by pietro-coretto** [FlamingTempura/bibtex-tidy#42]
The matching criteria for spotting duplicated entries works pretty well, although on some occasions when the search is performed with  '_Similar author and title_' option I get too many false positives. For example, these two entries are tagged as duplicated, but actually the only really matching filed is the `title`, 

```bib
@book{hr09,
	title        = {Robust statistics},
	author       = {Huber, Peter J. and Ronchetti, Elvezio M.},
	year         = 2009,
	publisher    = {John Wiley \& Sons, Inc., Hoboken, NJ},
	series       = {Wiley Series in Probability and Statistics},
	pages        = {xvi+354 pp. + loose erratum},
	doi          = {10.1002/9780470434697},
	isbn         = {978-0-470-12990-6},
	edition      = {Second}
}

@book{huber81,
	title        = {Robust statistics},
	author       = {Huber, Peter J.},
	year         = 1981,
	publisher    = {John Wiley \& Sons, Inc., New York},
	series       = {Wiley Series in Probability and Mathematical Statistics},
	pages        = {ix+308},
	isbn         = {0-471-41805-6}
}
```

**Comment by FlamingTempura** [comment]
Hey, thanks for the report. 

Unfortunately the "Similar author and title" algorithm is pretty basic and will result in false positives in some cases. 

It works by getting the first author name and title of two entries, removing punctuation, and checking if the result is the same for both entries. In your example the second author is ignored so both articles appear to be the same.

https://github.com/FlamingTempura/bibtex-tidy/blob/cf7ee5dba86762e104df7f764ee99cbb2f741a94/src/index.ts#L133

It could probably be improved but even Google Scholar makes mistakes when detecting duplicates :)

Closing this for now. If you have any suggestions for how the algorithm could be improved then feel free to reopen.
