### ISSUE TITLE
Is there a maximum file size?

### ISSUE THREAD

**Issue by adriancheok** [FlamingTempura/bibtex-tidy#420]
When I try to run bibtex-tidy on the web or desktop it says 0 files cleaned when I put in my entire bib file. But it works on the default file in the web site. Is there a maximum file size of the Bibtex file it can run on?

**Comment by FlamingTempura** [comment]
Hi @adriancheok - The hard limit is likely around 2GB (node.js memory limit). In practice it'll probably be very slow at 100mb.

Are you able to share the bibtex file that was causing the issue?

**Comment by FlamingTempura** [comment]
Closed as inactive
