### ISSUE TITLE
Bug: `--no-encode-url` still encodes URLs

### ISSUE THREAD

**Issue by chrisgrieser** [FlamingTempura/bibtex-tidy#422]
```bash
cat test.bib | bibtex-tidy --no-encode-urls
```

```bib
@incollection{BlattelMink2021,
  title         = {{Foobar}},
  author        = {foobar},
  url           = {https://doi.org/10.1007/978-3-658-17668-6_5}
}
% becomes
@incollection{BlattelMink2021,
  title         = {{Foobar}},
  author        = {foobar},
  url           = {https://doi.org/10.1007/978-3-658-17668-6\%5F5}
}
```

**Comment by FlamingTempura** [comment]
Fixed in v1.14.0 - url should no longer be encoded

**Comment by jdujava** [comment]
Testing this with v1.14.0, by default the URL is not encoded, but for some reason passing either `--encode-urls` or `--no-encode-urls` produces encoded URL.

**Comment by chrisgrieser** [comment]
can confirm, passing nothing keeps the URL unencoded, while `--no-encode-urls` results in the URL being encoded, basically the original problem.
