### ISSUE TITLE
bibtex-tidy takes perfectly good argv and destroys it with `.join`

### ISSUE THREAD

**Issue by flying-sheep** [FlamingTempura/bibtex-tidy#428]
there’s a reason that `argv` is an array, which is that individual elements can contain spaces. E.g. file paths. Please never `.join` it

https://github.com/FlamingTempura/bibtex-tidy/blob/98701a8bfb5a98ccd3ed43db679f525714599d72/src/cli/cli.ts#L25

**Comment by FlamingTempura** [comment]
I'm not sure if you intended to come off abrasively there but remember this is an open source project.

That said, I see how this is a legitimate issue. May be a while until I can get around to fixing this. PR welcome.

**Comment by flying-sheep** [comment]
Hi! I meant it more humorously, sorry that it came over that way.

I think it might be more robust to shop for a command line arg parser than to roll your own here.

That would also fix issues like https://github.com/FlamingTempura/bibtex-tidy/issues/419 (see https://github.com/FlamingTempura/bibtex-tidy/issues/419#issuecomment-2042144572 for what’s wrong there)

**Comment by FlamingTempura** [comment]
Fixed in v1.14.0

**Comment by flying-sheep** [comment]
Great, thanks!
