### ISSUE TITLE
Automatically standardise bibtex keys

### ISSUE THREAD

**Issue by CompRhys** [FlamingTempura/bibtex-tidy#44]
When drawing bib files from multiple sources you can end up with non-standard bibtex keys. it would be great to be able to standardise them automatically

**Comment by FlamingTempura** [comment]
Hey, thanks for the suggestion!

I've been keen to do this for a while but it's a pretty big project. I was thinking it could be formatted as `<Last Name Of First Author><Year><Significant Word From Title>` (like google scholar). However, bibtex-tidy currently does not parse the authors list. We'd also need to handle what should happen when there are duplicates.

So this is a bit of a wishlist item at the moment.

**Comment by FlamingTempura** [comment]
In the CLI you can now use `--generate-keys`. In the web app tick "Generate BibTeX keys". This will set the key of each entry to the form `<name><year><title>`.


This option is experimental so let me know if you find any problems with it.
