### ISSUE TITLE
the app does not recognise bib entries with colon in name

### ISSUE THREAD

**Issue by rriemann** [FlamingTempura/bibtex-tidy#5]
Dear all,

I noticed that the app does not recognise bib entries with a colon in the identifier.

Example entry:

```bib
@online{wiki:thereum2018,
title = "Ethereum",
journaltitle = {Wikipedia{,} The Free Encyclopedia},
url = {https://en.wikipedia.org/wiki/Ethereum},
urldate = {2018-02-06}
}
```

Result:

![Screenshot_20190906_163511](https://user-images.githubusercontent.com/111932/64436268-4e757a00-d0c4-11e9-98ab-8ae736f7e03b.png)

**Comment by FlamingTempura** [comment]
Looks like output is correct but the highlighting is wrong.

I have pushed a fix. Could you confirm it's solved your problem?

**Comment by rriemann** [comment]
Thank you for fixing!
