### ISSUE TITLE
Configuration as URL parameters

### ISSUE THREAD

**Issue by nzedler** [FlamingTempura/bibtex-tidy#50]
Love your tool, it would be great if the configuration of [https://flamingtempura.github.io/bibtex-tidy/](https://flamingtempura.github.io/bibtex-tidy/) was in the URL as parameters. Then one could just share the link with the correct configuration for a project.

**Comment by thisiscam** [comment]
Up on this one!
Would be nice if I can save the parameter settings through the url parameters.

**Comment by pedropaulofb** [comment]
I also loved your tool! Thanks for it!

The configuration as URL parameters would be the best option (and I vote for it), however, the option to export/import the configuration as a file would do the work.

**Comment by FlamingTempura** [comment]
This is a great suggestion. I'll take a look at implementing this.

Storing all options in the URL will make the URL very long. Might be avoidable by only storing differences with the default options.

**Comment by Pyrestone** [comment]
@FlamingTempura any update on this?

**Comment by thisiscam** [comment]
> This is a great suggestion. I'll take a look at implementing this.
> 
> Storing all options in the URL will make the URL very long. Might be avoidable by only storing differences with the default options.

FWIW, I don't think it matters a lot if the URL is long. I think most of us will basically 
1. come up with that URL by filling in the parameters in the web interface, 
2. store that URL string somewhere and
3.  just forget about it forever...

**Comment by FlamingTempura** [comment]
As of #344 options are persisted in the URL (thanks @thisiscam)
