### ISSUE TITLE
Sorting in Descending Order

### ISSUE THREAD

**Issue by shashankkotyan** [FlamingTempura/bibtex-tidy#6]
Is there a way to sort the bib entries in descending order in the web-version? 
I sort the bib entries according to the year. In this case, an option to sort in the descending order (reverse chronological order) would be beneficial.

**Comment by FlamingTempura** [comment]
There is not currently a way to do this but it should be an easy enough option to implement. I'll find some time to look into it.

**Comment by FlamingTempura** [comment]
You should now be able to sort fields in descending order by prefixing the field with a dash. E.g. `-year author` would sort by year in descending order, then within each year sort author in ascending order.

This is live on https://flamingtempura.github.io/bibtex-tidy/ and can be found in 'Sort bibliography entries'.

Tested with this example:
```bibtex
@article{greer,
	title={Foo},
    author={Greer},
    year=2010
   }
   
   @article{weiss,
	title={Bar},
    author={Weiss},
    year=2012
   }
   @article{charles,
	title={Hello},
    author={Charles},
    year=2008
   }
   @article{smith,
	title={Boo},
    author={Smith},
    year=2010
   }
   @article{antoin,
	title={Moo},
    author={Antoin},
    year=2010
   }
```

After tidy:
![flamingtempura github io_bibtex-tidy_(iPad) (1)](https://user-images.githubusercontent.com/1085434/77852356-266f7480-71d6-11ea-918d-78d27477d7d9.png)


Let me know if this does what you need. Apologies for taking so long to look at this!
