### ISSUE TITLE
issue with generating bibtex keys

### ISSUE THREAD

**Issue by tengyuma** [FlamingTempura/bibtex-tidy#62]
Thanks very much for the very convenient tools.

FWIW, it seems that when I chose "generating bibtex keys", sometimes there could be some errors. E.g., for the following entry 

@inproceedings{aristidou2008predicting,
	title        = {
		Predicting Missing Markers to Drive Real-Time Centre of Rotation

		Estimation
	},
	author       = {Aristidou, Andreas and Cameron, Jonathan and Lasenby, Joan},
	year         = 2008,
	booktitle    = {
		AMDO '08: Proceedings of the 5th international conference on Articulated

		Motion and Deformable Objects
	},
	location     = {Port d'Andratx, Mallorca, Spain},
	publisher    = {Springer-Verlag},
	address      = {Berlin, Heidelberg},
	pages        = {238--247},
	doi          = {http://dx.doi.org/10.1007/978-3-540-70517-8_23},
	isbn         = {978-3-540-70516-1}
}

After generating the bibtex keys, it becomes 

@inproceedings{aristidou2008{
		predicting missing markers to drive real-time centre of rotation

		estimation
	},
	title        = {
		Predicting Missing Markers to Drive Real-Time Centre of Rotation

		Estimation
	},
	author       = {Aristidou, Andreas and Cameron, Jonathan and Lasenby, Joan},
	year         = 2008,
	booktitle    = {
		AMDO '08: Proceedings of the 5th international conference on Articulated

		Motion and Deformable Objects
	},
	location     = {Port d'Andratx, Mallorca, Spain},
	publisher    = {Springer-Verlag},
	address      = {Berlin, Heidelberg},
	pages        = {238--247},
	doi          = {http://dx.doi.org/10.1007/978-3-540-70517-8_23},
	isbn         = {978-3-540-70516-1}
}

Thanks so much!

**Comment by FlamingTempura** [comment]
Newlines in the title were causing problems. Should be fixed now - thanks!
