### ISSUE TITLE
Tag bibtex-tidy releases

### ISSUE THREAD

**Issue by hamdanal** [FlamingTempura/bibtex-tidy#75]
Love this tool, thank you very much. This is a feature request to git tag the releases so that `pre-commit autoupdate` works correctly.

`pre-commit autoupdate` uses tags to [upgrade to latest versions](https://pre-commit.com/#using-the-latest-version-for-a-repository) of a tool. Currently pre-commit cannot know what is the commit for the latest release so the `autoupdate` command uses the latest commit available which may be a work in progress or broken. It would be nice tag the *"Release vX.Y.Z"* commits.

**Comment by FlamingTempura** [comment]
Thanks for the feedback!

I've updated the release process so a tag will be automatically created when I cut a release. https://github.com/FlamingTempura/bibtex-tidy/tags

Feel free to reopen if you have any issues.
