### ISSUE TITLE
Allow other option to remove duplicates

### ISSUE THREAD

**Issue by bixiou** [FlamingTempura/bibtex-tidy#9]
Your very nice tool didn't produce the result I was looking for. I have duplicated entries with different IDs and duplicated entries with same IDs. What I want is merge all duplicated entries with same IDs, but keep the other duplicates. (This is because in a large LaTeX document, I have references to the different kinds of IDs, so I have to keep all of them). It would be nice to add such option.

**Comment by FlamingTempura** [comment]
I have added a few options for merging, including just checking for duplicate IDs (keys). Could you try it out and let me know if it does what you need?

![image](https://user-images.githubusercontent.com/1085434/78504662-80d47c00-7766-11ea-955b-45ba95a435ba.png)

**Comment by bixiou** [comment]
This is exactly what I needed! Thank you so much for this really prompt fix!
Btw, I needed to merge on matching keys but maybe most people would need similar author and title (just saying for the default choice).
