### ISSUE TITLE
Cannot parse generated output.

### ISSUE THREAD

**Issue by m1dnight** [FlamingTempura/bibtex-tidy#98]

**Comment by FlamingTempura** [comment]
Could you provide more information on the issue you are having?

**Comment by m1dnight** [comment]
I'm sorry, I must have submitted this by accident. 

The entry below is the one that errors out. I can paste it like it is pasted here, and it tidies, but the result of the tidier is no longer valid. 

So input -> tidy -> output -> tidy  results in an error on the double quotes. 

```@inbook{099e8d9aba174658aa5934e874f78eb9,  title     = "PrintTalk: a constraint-based imperative DSL for 3D printing",  abstract  = "We present PrintTalk, a DSL to {"}program{"} 3D objects, called {"}gadgets{"}. PrintTalk also features {"}topologies{"}, which are predefined spacial arrangements of gadgets. Gadgets are composed by executing a gadget script (possibly consisting of subscripts) that 'draws' the gadget in the 3D scene. However, executing the script also returns a number of constraint variables. These variables can be constrained inside the gadget and can also be bound outside the gadget in order to constrain the produced gadgets after the facts. This is the essence of the gadget composition mechanism of PrintTalk.PrintTalk is implemented in DrRacket. Running a PrintTalk program generates a file that is sent to the 3D printer. We validate PrintTalk qualitatively by comparing the code for complex gadgets with the code needed to print those gadgets in existing languages.",  keywords  = "PrintTalk, Domain Specific Language, DSL, Design Languages, 3D Modelling, CAD, Constraints",  author    = "Jef Jacobs and Jens Nicolay and {De Troyer}, Christophe and {De Meuter}, Wolfgang",  year      = "2021",  month     = "10",  day       = "18",  doi       = "10.1145/3486603.3486778",  language  = "English",  pages     = "11--20",  booktitle = "DSM 2021: Proceedings of the 18th ACM SIGPLAN International Workshop on Domain-Specific Modeling",  publisher = "ACM", }```


I tried making a minimal example with the input below, and I think the problematic case is that there is `{"}` in a value wrapped in `""`. 
I have been skimming the biblatex package, but I can't seem to spot where it says it's valid or invalid syntax. I'm a bit pressed for time now, but I thought I'd report it anyway. 
The best I could find was http://www.bibtex.org/Format/, where the example shows a string wrapped in double quotes, and contains curly braces. 


Thanks for an amazing tool.

```
@book{sweig42,
	title        = "The {"}impossible{"} book",
	author       = {Stefa{n} Sweig},
	year         = 1942,
	month        = mar,
	publisher    = {Dead Poet Society}
}

```

**Comment by FlamingTempura** [comment]
Thanks. I haven't seen the `{"}` method of escaping a double quote before. The parser does not support it. 

The parser sees the double quote, thinks the field has ended, then sees the close brace and thinks the entry has ended. It assumes the rest of the entry is a comment.

Then it converts the double quoted value to a braced value. Since the value contains an open brace but not a closed one (due to the parser not seeing it), we end up with a syntax error. This is a bug.

```diff
- abstract  = "We present PrintTalk, a DSL to {"
+ abstract  = {We present PrintTalk, a DSL to {} <-- unclosed block
```

So there's a couple of things to consider here:
* Whether to support `{"}` (like you I'm struggling to find this documented anywhere)
* Ensuring conversion of quoted value to braced values does not generate invalid syntax.

**Comment by FlamingTempura** [comment]
I have added support for escaped quotes so this is now fixed. I've tested your input:

```bibtex
@inbook{099e8d9aba174658aa5934e874f78eb9,  title     = "PrintTalk: a constraint-based imperative DSL for 3D printing",  abstract  = "We present PrintTalk, a DSL to {"}program{"} 3D objects, called {"}gadgets{"}. PrintTalk also features {"}topologies{"}, which are predefined spacial arrangements of gadgets. Gadgets are composed by executing a gadget script (possibly consisting of subscripts) that 'draws' the gadget in the 3D scene. However, executing the script also returns a number of constraint variables. These variables can be constrained inside the gadget and can also be bound outside the gadget in order to constrain the produced gadgets after the facts. This is the essence of the gadget composition mechanism of PrintTalk.PrintTalk is implemented in DrRacket. Running a PrintTalk program generates a file that is sent to the 3D printer. We validate PrintTalk qualitatively by comparing the code for complex gadgets with the code needed to print those gadgets in existing languages.",  keywords  = "PrintTalk, Domain Specific Language, DSL, Design Languages, 3D Modelling, CAD, Constraints",  author    = "Jef Jacobs and Jens Nicolay and {De Troyer}, Christophe and {De Meuter}, Wolfgang",  year      = "2021",  month     = "10",  day       = "18",  doi       = "10.1145/3486603.3486778",  language  = "English",  pages     = "11--20",  booktitle = "DSM 2021: Proceedings of the 18th ACM SIGPLAN International Workshop on Domain-Specific Modeling",  publisher = "ACM", }
```

The tidied output:
```bibtex
@inbook{099e8d9aba174658aa5934e874f78eb9,
	title        = "PrintTalk: a constraint-based imperative DSL for 3D printing",
	author       = "Jef Jacobs and Jens Nicolay and {De Troyer}, Christophe and {De Meuter}, Wolfgang",
	year         = 2021,
	month        = 10,
	day          = 18,
	booktitle    = "DSM 2021: Proceedings of the 18th ACM SIGPLAN International Workshop on Domain-Specific Modeling",
	publisher    = "ACM",
	pages        = "11--20",
	doi          = "10.1145/3486603.3486778",
	abstract     = "We present PrintTalk, a DSL to {"}program{"} 3D objects, called {"}gadgets{"}. PrintTalk also features {"}topologies{"}, which are predefined spacial arrangements of gadgets. Gadgets are composed by executing a gadget script (possibly consisting of subscripts) that 'draws' the gadget in the 3D scene. However, executing the script also returns a number of constraint variables. These variables can be constrained inside the gadget and can also be bound outside the gadget in order to constrain the produced gadgets after the facts. This is the essence of the gadget composition mechanism of PrintTalk.PrintTalk is implemented in DrRacket. Running a PrintTalk program generates a file that is sent to the 3D printer. We validate PrintTalk qualitatively by comparing the code for complex gadgets with the code needed to print those gadgets in existing languages.",
	keywords     = "PrintTalk, Domain Specific Language, DSL, Design Languages, 3D Modelling, CAD, Constraints",
	language     = "English"
}
```

Let me know if you notice any issues!
